app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Static:homepage }
    methods: GET

app_about:
    path:     /about
    defaults: { _controller: AppBundle:Static:about }
    methods: GET

app_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Static:contact }
    methods: GET|POST

app_search:
    path:     /search
    defaults: { _controller: AppBundle:Search:searchbar }
    methods: GET

app_profile:
    path:     /profile/{userId}
    defaults: { _controller: AppBundle:Static:profile }
    methods: GET

app_admin_pageList:
    path:     /admin/page/
    defaults: { _controller: AppBundle:Page:list }
    methods: GET

app_admin_pageEdit:
    path:     /admin/page/{id}/edit
    defaults: { _controller: AppBundle:Page:edit }
    methods: GET|POST
    requirements:
        id: \d+

app_admin_functionList:
    path:     /admin/function/
    defaults: { _controller: AppBundle:EZFunction:list }
    methods: GET

app_admin_functionEdit:
    path:     /admin/function/{id}/edit
    defaults: { _controller: AppBundle:EZFunction:edit }
    methods: GET|POST
    requirements:
        id: \d+

app_admin_functionCreate:
    path:     /admin/function/create
    defaults: { _controller: AppBundle:EZFunction:create }
    methods: GET|POST

app_admin_functionRemove:
    path:     /admin/function/{id}/remove
    defaults: { _controller: AppBundle:EZFunction:remove }
    methods: DELETE

app_functionShow:
    path:     /function/{id}
    defaults: { _controller: AppBundle:EZFunction:show }
    methods: GET
    requirements:
        id: \d+

app_notfound:
    path:     /notfound
    defaults: { _controller: AppBundle:Static:notfound }
    methods: GET
