app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Static:homepage }
    methods: GET
    
app_about:
    path:     /about
    defaults: { _controller: AppBundle:Static:about }
    methods: GET

app_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Static:contact }
    methods: GET|POST

app_search:
    path:     /search
    defaults: { _controller: AppBundle:Static:searchbar }
    methods: POST

app_profile:
    path:     /profile/{userId}
    defaults: { _controller: AppBundle:Static:profile }
    methods: GET

app_function:
    path:     /function/{functionId}
    defaults: { _controller: AppBundle:Static:function }
    methods: GET

app_admin_pageList:
    path:     /admin/page/
    defaults: { _controller: AppBundle:Page:list }
    methods: GET
    
app_admin_pageEdit:
    path:     /admin/page/{id}/edit
    defaults: { _controller: AppBundle:Page:edit }
    methods: GET|POST
    requirements:
        id:  \d+