app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Static:homepage }
    methods: GET
    
app_about:
    path:     /about
    defaults: { _controller: AppBundle:Static:about }
    methods: GET

app_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Static:contact }
    methods: GET|POST
